# Generated by Django 3.2.25 on 2025-10-27 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Спортивний Зал', max_length=150)),
                ('short_description', models.TextField(default='Сучасний фітнес-комплекс із індивідуальними та груповими тренуваннями. Професійні тренери, комфортні умови, онлайн-запис.')),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('work_hours', models.CharField(blank=True, default='Пн–Пт: 07:00–22:00; Сб–Нд: 09:00–20:00', max_length=200)),
                ('map_embed', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_guard', models.BooleanField(default=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Інформація про зал (один запис)',
                'verbose_name_plural': 'Інформація про зал (один запис)',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('duration_label', models.CharField(help_text='Напр.: 1 день / 30 днів / 90 днів / 365 днів', max_length=120)),
                ('price_uah', models.DecimalField(decimal_places=2, help_text='Ціна в гривнях', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифи',
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
