# Generated by Django 3.2.25 on 2025-10-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteinfo_tariff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('category', 'sort_order', 'name'), 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифи'},
        ),
        migrations.AddField(
            model_name='tariff',
            name='category',
            field=models.CharField(choices=[('INDIVIDUAL', 'Індивідуальні тренування'), ('DANCE', 'Танці'), ('YOGA', 'Йога'), ('CROSSFIT', 'Кросфіт'), ('PILATES', 'Пілатес'), ('STRETCHING', 'Стретчинг'), ('MARTIAL', 'Бойові мистецтва'), ('FITNESS', 'Фітнес (групові)'), ('BODYBUILDING', 'Тренажерний зал / Бодібілдинг'), ('OTHER', 'Інше')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['category', 'sort_order'], name='core_tariff_categor_4784fb_idx'),
        ),
    ]
