# Generated by Django 3.2.25 on 2025-10-06 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Чоловіча'), ('female', 'Жіноча'), ('other', 'Інша')], max_length=16)),
                ('role', models.CharField(choices=[('client', 'Клієнт'), ('trainer', 'Тренер'), ('manager', 'Менеджер'), ('head_manager', 'Головний менеджер')], max_length=32)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('specialization', models.CharField(blank=True, max_length=128, null=True)),
                ('work_time', models.CharField(blank=True, max_length=128, null=True)),
                ('manager_status', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
