# Generated by Django 3.2.25 on 2025-10-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Чоловіча'), ('female', 'Жіноча'), ('other', 'Інша')], max_length=16, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='manager_status',
            field=models.CharField(blank=True, help_text='Опціонально: напр., Менеджер зміни / Менеджер залу', max_length=64, null=True, verbose_name='Статус менеджера'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Клієнт'), ('trainer', 'Тренер'), ('manager', 'Менеджер')], max_length=32, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('personal', 'Індивідуальні тренування'), ('dance', 'Танці'), ('yoga', 'Йога'), ('crossfit', 'Кросфіт'), ('pilates', 'Пілатес'), ('stretching', 'Стретчинг'), ('other', 'Інше')], max_length=32, null=True, verbose_name='Спеціалізація'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('trainer', 'Тренер'), ('senior_trainer', 'Старший тренер'), ('head_trainer', 'Головний тренер залу')], help_text='Напр., Тренер / Старший тренер / Головний тренер залу', max_length=32, null=True, verbose_name='Статус тренера'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_time',
            field=models.CharField(blank=True, help_text='Вільний текст: напр. Пн–Пт 09:00–18:00', max_length=128, null=True, verbose_name='Час роботи'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='accounts_pr_role_fae1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='accounts_pr_gender_56b26b_idx'),
        ),
    ]
