# Generated by Django 3.2.25 on 2025-10-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251012_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('personal', 'Індивідуальні тренування'), ('dance', 'Танці'), ('yoga', 'Йога'), ('crossfit', 'Кросфіт'), ('pilates', 'Пілатес'), ('stretching', 'Стретчинг'), ('martial_arts', 'Бойові мистецтва'), ('fitness', 'Фітнес'), ('bodybuilding', 'Бодібілдинг'), ('other', 'Інше')], max_length=32, null=True, verbose_name='Спеціалізація'),
        ),
    ]
